### ISSUE TITLE
Make sure directories exist

### ISSUE THREAD

**Issue by 0-wiz-0** [mrusme/neonmodem#53]
neonmodem just exits loudly if `$HOME/.config` (for `connect`) or `$HOME/.cache` (always) do not exist.
I think it should create the directories if it needs them.

**Comment by mrusme** [comment]
@0-wiz-0 neonmodem is getting these directories at [this point](https://github.com/mrusme/neonmodem/blob/4cd77b1239a3be0c8805ad541c2b33b7dfc5785a/config/config.go#L129), using [Go's `os` package](https://pkg.go.dev/os#UserCacheDir). Those function use the environment variables set **by the user** and return those values. As written in the documentation:

> UserCacheDir returns the default root directory to use for user-specific cached data. Users should create their own application-specific subdirectory within this one and use that.
>
> On Unix systems, it returns $XDG_CACHE_HOME as specified by https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html if non-empty, else $HOME/.cache. On Darwin, it returns $HOME/Library/Caches. On Windows, it returns %LocalAppData%. On Plan 9, it returns $home/lib/cache.
>
> **If the location cannot be determined (for example, $HOME is not defined), then it will return an error.**

I don't **believe** it is a good idea for *a random program* to just create the directories that a user has specified as ENV, e.g. `$XDG_CACHE_HOME`, hence the one thing that I found sensible was to let neonmodem *crash loudly*, so that the user takes care to fix his ENV.

However, having that said, I haven't read deeper into especially the XDG/Freedesktop specification to understand whether programs **should** in fact create these directories if they're non-existent. 

If you have any info that explicitly points out that neonmodem is not behaving in a standard way free to re-open the issue. :-)
