### ISSUE TITLE
panic: Error(s) loading system(s) → crash → stackdump

### ISSUE THREAD

**Issue by bruceleerabbit** [mrusme/neonmodem#63]
```
$ torsocks neonmodem connect --type lemmy --url https://links.hackliberty.org
Please enter your username or email: bruceleerabbit
Please enter your password (will not echo):
Successfully added new connection!
```
```
$ torsocks neonmodem
panic: Error(s) loading system(s)

goroutine 1 [running]:
github.com/mrusme/neonmodem/cmd.glob..func1(0x1771140?, {0xe973eb?, 0x0?, 0x0?})
        /home/runner/work/neonmodem/neonmodem/cmd/root.go:128 +0x268
github.com/spf13/cobra.(*Command).execute(0x1771140, {0xc000022240, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1771140)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/mrusme/neonmodem/cmd.Execute(0xc0000061a0?)
        /home/runner/work/neonmodem/neonmodem/cmd/root.go:141 +0x3e
main.main()
        /home/runner/work/neonmodem/neonmodem/neonmodem.go:13 +0x25
```
Followed this for the undocumented proxy guidance:

https://github.com/mrusme/neonmodem/issues/1

By editing the config file (in case torsocks is the problem), e.g.:
```
sed -i -e "/proxy =/Is@''@'http://localhost:1881'@" ~/.config/neonmodem.toml
```
```
$ neonmodem
panic: Error(s) loading system(s)

goroutine 1 [running]:
github.com/mrusme/neonmodem/cmd.glob..func1(0x1771140?, {0xe973eb?, 0x0?, 0x0?})
        /home/runner/work/neonmodem/neonmodem/cmd/root.go:128 +0x268
github.com/spf13/cobra.(*Command).execute(0x1771140, {0xc000022240, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1771140)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/mrusme/neonmodem/cmd.Execute(0xc0000061a0?)
        /home/runner/work/neonmodem/neonmodem/cmd/root.go:141 +0x3e
main.main()
        /home/runner/work/neonmodem/neonmodem/neonmodem.go:13 +0x25
```

Not sure why there are github references in that stack dump. I know nothing about go but it irks me to make any connection to MS servers or to have any dependency on MS. If there’s any way to get a full complete copy of the software, free and clear from MS/Google/Facebook/Amazon/Cloudflare and similar junk entities, that would be plan A.

**Comment by mrusme** [comment]
Thank you for reporting.

The issue you referred to details the use of `HTTP_PROXY`, which is for an HTTP proxy, not a SOCKS proxy (`torsocks`). See [this](https://oxylabs.io/blog/socks-vs-http-proxy). There are ways to [enable HTTP proxying via `torrc`](https://stackoverflow.com/questions/28520028/tor-as-http-proxy-instead-socks), you could give it try. Another idea would be to try to use [proxychains-ng](https://github.com/rofl0r/proxychains-ng) and not set a `HTTP_PROXY`. Haven't tested it, but it might work out of the box. I agree that support for Tor, one way or the other, would be desirable. If neither of these solutions work, implementing dedicated SOCKS proxy support would be required.

The second thing is the actual crash dump, which should not happen. Will investigate this.

Last but not least, the *github references*. Packages (dependencies) in Go are namespaced to the locations they are hosted on. For example Cobra is hosted at https://github.com/spf13/cobra, which is where the Go package manager (`go get`) will look for and download the dependency. This is similar to how `docker pull` looks for containers on a specific registry, which is namespaced into the container name (e.g. `docker.io/postgres:alpine`). *Neon Modem Overdrive* does not send any data to Microsoft servers, unless any of the systems you try to connect to are hosted on Microsoft infrastructure. The reason you're seeing github.com URLs is because it's part of the dependency name in Go.

**Comment by bruceleerabbit** [comment]
> The issue you referred to details the use of HTTP_PROXY, which is for an HTTP proxy, not a SOCKS proxy (torsocks). See this. 

That link goes to a Cloudflare site, which is inside a walled garden that blocks various demographics of people. But I understand the difference. Apparently neonmodem is getting them backwards. I have both a SOCKS proxy (which typically listens on port 9050) and an HTTP proxy (privoxy) on port 1881. Many apps use my HTTP proxy without issues. E.g. these commands all work on my system:
```
$ curl --proxy 'https://127.0.0.1:1881'
$ http_proxy=http://127.0.0.1:1881 lynx
$ openssl s_client -proxy '127.0.0.1:1881'
$ aria2c --all-proxy=http://127.0.0.1:1881/
$ cclive --proxy 'http://127.0.0.1:1881'
$ wkhtmltopdf --proxy 'http://127.0.0.1:1881'
```
Torsocks also works on those same commands, without the proxy parameter. Torsocks has some defects but misrepresenting a SOCKs proxy as an HTTP proxy would not be one of them. Something is likely fundamentally wrong with how neonmodem is using the proxy.

> This happens during compile time, not during runtime.

I struggle to understand that because I understood the command I ran to be a runtime activity carried out by a binary executable (thus already compiled). I did not compile neonmodem as far as I know. The `README.md` file says:

> The binary is called `neonmodem`. Feel free to move it to e.g. `/usr/local/bin`.

and from there simply says configuration is needed.

If there is some kind of self-compiling mechanism, then shouldn’t the compilation have happened on the first execution where the `connect` command was supplied?  There is apparently a transparency problem here. If the app is reaching out to MS servers and self compiling, that should be disclosed to the user because it’s unexpected. A message like “this is the first execution so contacting github.com to self-compile”. The README and --help docs make no mention of compilation. 

BTW, the --help docs shows that the `connect` command is always supplied to neonmodem. But then the readme says:

> After setup Neon Modem can be launched by calling neonmodem without any arguments.

So the --help page incorrectly states `connect` is a necessary parameter.

**Comment by bruceleerabbit** [comment]
Oh shit. I just remembered that golang has mixed up SOCKS and HTTP proxies in the standard libraries:

https://github.com/emersion/hydroxide/issues/110

How can such a fundamental screwup in the standard code libraries carry on so long?  This is bizarre.

**Comment by bruceleerabbit** [comment]
Since the language libs got it backwards, I tried reversing the config and supplying the SOCKS proxy port instead of the HTTP proxy port in `~/.config/neonmodem.toml` and it made no difference. So the proxy protocol being incorrect in the go libraries may not even be related to the crash.

**Comment by mrusme** [comment]
> In any case, there is apparently a transparency problem here.

This is not the case, it is much rather an *understanding* problem. Kindly familiarize yourself with Go, if you are concerned about the stack trace and the brief explanation I gave you is insufficient to you. I also invite you to go through the source code and confirm for yourself that none of what you're suggesting is in fact happening.

> If there is some kind of self-compiling mechanism

No such thing. As said before, kindly familiarize yourself with Go if you are curious about the output and my explanation is not sufficient to you.

As for the proxy issues in general, I've pointed out before that `HTTP_PROXY` (via [`http.Transport`](https://pkg.go.dev/net/http#Transport) was implemented and confirmed to be working, but no other method. If you require `neonmodem` to work with different types of proxies, please open a new feature request.

> So the proxy protocol being incorrect in the go libraries may not even be related to the crash.

Correct, the crash might be unrelated, hence I said:

>> The second thing is the actual crash dump, which should not happen. Will investigate this.

Even if it is related, `neonmodem` should not crash due to a faulty proxy configuration.

> BTW, the --help docs shows that the connect command is always supplied to neonmodem.

```sh
$ neonmodem --help
neonmodem is a bulletin board system (BBS) text user interface written in Go, supporting Discourse and Lemmy.
More info available on https://xn--gckvb8fzb.com/projects/neonmodem

Usage:
  neonmodem [flags]
  neonmodem [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  connect     Connect to BBS
  help        Help about any command

Flags:
      --debug   Debug output
  -h, --help    help for neonmodem

Use "neonmodem [command] --help" for more information about a command.
```

I don't know what you're referring to.

**Comment by mrusme** [comment]
Systems loading was made soft-failing, meaning that in case a system cannot be loaded for whatever reason -- in your case due to proxy issues -- NMO will continue to launch, but the specific systems won't be available for use. As usual, you can find more information on **why** the system(s) failed inside `~/.cache/neonmodem.log`.

As stated before, depending on why exactly the Lemmy system fails to load for you, it might be due to your specific proxy setup not working. In that case, please open a feature request with the exact setup details (proxy configuration, `neonmodem.toml` with censored/removed credentials), including the log output from NMO.

**Comment by bruceleerabbit** [comment]
> Systems loading was made soft-failing, meaning that in case a system cannot be loaded for whatever reason -- in your case due to proxy issues -- NMO will continue to launch, but the specific systems won't be available for use. 

That’s a bit vague but sounds dangerous. If a user specifies a proxy and the proxy fails for some reason, it is extremely important that the app not continue to function over the network in a proxyless state. Users rely on proxies to protect from unwanted disclosure. I would not envision many users wanting proxies to be opportunistic. Unwitting opportunistic proxying could really burn someone. Hydroxide exposes users to invisible proxy failures which is a quite bad idea.

> Kindly familiarize yourself with Go, … pkg.go.dev

That website is in a Tor-hostile walled garden. Gives a 403 forbidden. It’s a shame that it seems to be the official resource of the Go language. Considering the Go language inherenly has this problem of exclusion and non-transparency, the Go project is not interested in my demographic of people learning about Go and as such I have to say it’s mutual because of that propensity for exclusion. A programming language should have openly accessible inclusive resources. 

> As usual, you can find more information on why the system(s) failed inside ~/.cache/neonmodem.log.

That is undocumented (no mention of `neonmodem.log` in the readme and not in the `--help` pages; no mention of the Log config parameter which I only discovered by looking at the config file). 

The error suggests that a github login is needed:

```
{"level":"error","caller":"cmd/root.go:97","msg":"error loading system: 401 Unauthorized: incorrect_login","stacktrace":"github.com/mrusme/neonmodem/cmd.loadSystems\n\t/home/runner/work/neonmodem/neonmodem/cmd/root.go:97\ngithub.com/mrusme/neonmodem/cmd.glob..func1\n\t/home/runner/work/neonmodem/neonmodem/cmd/root.go:123\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992\ngithub.com/mrusme/neonmodem/cmd.Execute\n\t/home/runner/work/neonmodem/neonmodem/cmd/root.go:141\nmain.main\n\t/home/runner/work/neonmodem/neonmodem/neonmodem.go:13\nruntime.main\n\t/opt/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:250"}
{"level":"error","caller":"cmd/root.go:126","msg":"401 Unauthorized: incorrect_login","stacktrace":"github.com/mrusme/neonmodem/cmd.glob..func1\n\t/home/runner/work/neonmodem/neonmodem/cmd/root.go:126\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992\ngithub.com/mrusme/neonmodem/cmd.Execute\n\t/home/runner/work/neonmodem/neonmodem/cmd/root.go:141\nmain.main\n\t/home/runner/work/neonmodem/neonmodem/neonmodem.go:13\nruntime.main\n\t/opt/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:250"}
```

I see no github login parameters in the config file. The error msg itself (“401 Unauthorized: incorrect_login”) is likely erroneous.

**Comment by mrusme** [comment]
First of all, let me say that I genuinely appreciate any constructive bug report, feature request, and other feedback. Having that said, statements like:

> That’s a bit vague but sounds dangerous. If a user specifies a proxy [...] quite bad idea.

... give me the feeling that no matter what I reply to you, you try to take my response and twist it into something it never was. I'm assuming that this behavior is unintentional from your side, yet I'd kindly ask to not continuously try to put things in a bad light, unless you have hard evidence that there are in fact things happening that should not -- in which case I'm happy for you to point them out so a fix can be implemented. Half-baked assumptions and guesses aren't something to throw around in an perceived attempt to make something appear fishy, especially not if you're actively seeking for support.

Back to the topic at hand: I never stated that NMO would *continue to function over the network in a proxyless state*. In fact I said the exact opposite: 

>> Systems loading was made soft-failing, meaning that in case a system cannot be loaded for whatever reason -- in your case due to proxy issues -- NMO will continue to launch, but **the specific systems won't be available for use**.

In my local tests, when the proxy was unavailable or logging on to it did not succeed, NMO would throw an error in the log but continue to load without the specific system (e.g. Lemmy) being functional.

If you have documented evidence that this is not the case and NMO indeed continues to connect to the system in question even though the proxy is not available, kindly open a bug report.

> That website is in a Tor-hostile [...] openly accessible inclusive resources.

You might realize that this remark, even though it seems important to you, doesn't exactly move the conversation forward. If you have ideas on how to improve the Go programming language or the resources it uses it is probably better to direct them towards the [golang team](https://github.com/golang).

PS: Not sure why you're wasting precious Onion network capacity on browsing pkg.go.dev, but you can instead use the offline `go doc` command (e.g. `go doc net`).

> That is undocumented (no mention of neonmodem.log in the readme [...]

As you appear to enjoy writing long form content, I invite you to open pull-requests whenever you see that there's room for improvement. This is how open-source projects thrive. 👍🏼 

> I see no github login parameters in the config file. The error msg itself (“401 Unauthorized: incorrect_login”) is likely erroneous.

This message has nothing to do with GitHub logins. Again, do not confuse stack traces listing package names and namespaces with actual attempts to connect to the respective URLs.

> if multiple accounts are configured, there is no mechanism to select an account to login to. NMO simply connects to the first profile in the config file.

It should connect to every configured system. If that's not the case, please open a dedicated bug report with your specifics.

> when pasting a password from the clipboard into the NMO prompt, apparently it sometimes adds leading or trailing junk [...]

This not the case. Probably you copied something odd or your clipboard and or Terminal are to blame. If you find a way to reproduce it, please open a bug report with the exact steps to do so.

> the error msg is misleading because it does not include the name of the server where the login was attempted.

True, this was fixed in the commit that fixed the `panic` reported here.

> when it launches, it gives no indication of which account it connected to

Press `C-e` when NMO launched and you see a list of all accounts that are online, as described in the [readme](https://github.com/mrusme/neonmodem?tab=readme-ov-file#navigation).

> the screen shows no content.. just “no items found”. Perhaps it is incompatible with links.hackliberty.org

It should be. I assume you're using an older release which had issues with a newer version of Lemmy. Either build the current `master` yourself or wait for the next release, that I'm preparing as of writing this.

> gives a stack dump if url = 'https://links.hackliberty.org' is replaced with url = 'https://snb3ufnp67uudsu25epj43schrerbk7o5qlisr7ph6a3wiez7vxfjxqd.onion' The crash occurrs reguardless of whether a proxy is configured, or whether torsocks is used.

No more stack dump since the commit that fixed this issue. However, the system likely won't function, mainly because your computer probably can't resolve the domain. In the log it should point out why it won't connect.
